<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Irappa" name="Testfirefox" tests="2" failures="0" timestamp="12 Sep 2018 11:23:38 GMT" time="30.021" errors="0">
  <testcase name="@AfterMethod closeApplication" time="0.0" classname="com.swc.testscripts.InvalidLogin">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.swc.generic.BaseTest.closeApplication(BaseTest.java:62)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod closeApplication -->
  <testcase name="testbInvalidLogin" time="11.397" classname="com.swc.testscripts.InvalidLogin"/>
  <testcase name="testValidLogin" time="0.002" classname="com.swc.testscripts.U_LoginPage">
    <skipped/>
  </testcase> <!-- testValidLogin -->
</testsuite> <!-- Testfirefox -->
